### PR TITLE
Handles example bugfixes

### PR DESCRIPTION
**Pull request by okrad**

### CODE REVIEW

**Comment by NicolasRannou** [comment]
Thanks @okrad ! Does that fix all the offsets issues?

**Comment by okrad** [comment]
No, I didn't have much time to look into those issues, but probably are on my side...

**Comment by NicolasRannou** [comment]
Not sure, maybe it is an issue in AMI - when you run the widgets example, does it work as expected?

**Comment by okrad** [comment]
The example looks good to me, there are some widgets that don't work (for example the Ellipse, although it works on my machine, and the CrossRuler), but as for the positioning it seems to work.

The issues I had was due to the fact that I didn't set the worldPosition on the widgets after istantiating them, but thanks to the example I found out what the problem was.

**Pull request merged**
