### PR TITLE
add a new ami logo

### PR DESCRIPTION
**Pull request by tibetegya**
##### What does this PR do?
- Add a new logo for the ami imaging javascript toolkit
##### Description of Task to be completed?
- Add png and svg logos
##### Any background context you want to provide?
<div>
drawing
drawing
</div>

### CODE REVIEW

**Comment by NicolasRannou** [comment]
Awesome! I like it! Can you also provide
* a logo with the icon on left and text on right?
* just "ami" with the "i" replaced by the logo
* logo on left + ami on right (not written medical imaging JS toolkit)
* a version of the logo just with borders (not filled content)

**Comment by tibetegya** [comment]
@NicolasRannou Done just check the assets folder for the updated logos

**Comment by NicolasRannou** [comment]
Awesome, one (easy to fix I hope) thing, the font is not the same everywhere, I really liked the one you used in the first message of this PR.

Which font is it BTW?

Should be good to go after that!

**Comment by tibetegya** [comment]
It is actually the same its called "ubuntu" https://design.ubuntu.com/font/

**Comment by NicolasRannou** [comment]
@tibetegya checkout this one for instance: https://github.com/FNNDSC/ami/blob/88d347f2216f591463f8f474822b07417d9fc86d/assets/ami_logo_plus_text.svg

The font seems different -

I like to have the ubuntu font, great for open source project :)

**Comment by tibetegya** [comment]
Its the same. Just small

**Comment by NicolasRannou** [comment]
Thanks!

**Comment by NicolasRannou** [comment]
ami_logo_side_x_side

**Comment by NicolasRannou** [comment]
ami_logo_plus_text

**Pull request merged**
