### PR TITLE
Add opacity uniform to data shader

### PR DESCRIPTION
**Pull request by eduardor2k**
Changes to implement #290 feature.

It's now possible to change the slider opacity value directly.

### CODE REVIEW

**Comment by PtiLuky** [comment]
You are overriding any opacity in data (Inverting had already a problem because it replace the opacity by 1.).

I'd suggest something like that: 
```js

  if(uInvert == 1){
    dataValue = vec4(1.) - dataValue;
    // keep the same opacity
    dataValue.a = 1. - dataValue.a;
  }

  dataValue.a = dataValue.a*uOpacity;
```

_And should we check if uOpacity is in [0.0 ; 1.0] range or it's ok?_

**Comment by NicolasRannou** [comment]
I'm not too sure about inverting the alpha channel: `dataValue.a = 1. - dataValue.a;`

Doing it this way means that any visible pixel will become invisible, instead of just inverting the color.

**Comment by PtiLuky** [comment]
With two consecutive inversions, the alpha is supposed to be unchanged ?

**Comment by NicolasRannou** [comment]
Oh you are right I missed it. Let's do:
```
dataValue.xyz = vec3(1.) - dataValue.xyz;
```
and if that doesn't work:
```
dataValue = vec4(1., 1., 1., 0.) - dataValue;
```

**Comment by eduardor2k** [comment]
@PtiLuky Hi, thanks for your feedback

I didn't mind overriding the alpha value, because if the numberOfChannels == 1, alpha is set to 1, but  i think as you said, it's better to not override the alpha value, because maybe in the future someone will change the value of alpha and would not see the changes because i'm overriding the value. 

I did not see a check in "shaders.layer.fragment" to verify that the values of uOpacity0 are in 0:1 range, i think it's better to check that this value is correct on the app code, instead of the shader code.

**Comment by eduardor2k** [comment]
@NicolasRannou the first example doesn't work, it makes everything transparent.

    dataValue.xyz = vec3(1.) - dataValue.xyz;

The second one works

      if(uInvert == 1){
        dataValue = vec4(1., 1., 1., 0.) - dataValue;
        // keep the same opacity
        dataValue.a = 1. - dataValue.a;
     }

 but has the same behavior than before (i think because we are overriding the alpha channel anyway)

     if(uInvert == 1){
        dataValue = vec4(1.) - dataValue;
        // keep the same opacity
        dataValue.a = 1. - dataValue.a;
     }

**Comment by PtiLuky** [comment]
If you use Nicolas' suggestion, you don't have to add the second "correction" line.
So the solution is either: 
```
if(uInvert == 1){
    dataValue.xyz = vec3(1.) - dataValue.xyz;
 }
```
or
```
if(uInvert == 1){
    dataValue = vec4(1., 1., 1., 0.) - dataValue; // alpha will be negative
    // keep the same opacity
    dataValue.a = - dataValue.a; // change alpha to positive
 }
```

**Comment by eduardor2k** [comment]
@PtiLuky thanks

I think it's cleaner with the first example, separating lut from opacity

**Comment by NicolasRannou** [comment]
I was suggesting:
```
if(uInvert == 1){
    dataValue = vec4(1., 1., 1., 0.) - dataValue; // do not touch alpha
 }
```

**Comment by eduardor2k** [comment]
@NicolasRannou I've tried the code and doesn't seem to work, the layer appears black, maybe i'm doing something wrong.

Maybe i'm not understanding the code correctly, but this example:

    if(uInvert == 1){
        dataValue.xyz = vec3(1.) - dataValue.xyz;
    }

You are only changing xyz and the alpha channel stays unmodified

    if(uInvert == 1){
       dataValue = dataValue - vec4(1., 1., 1., 0.); // do not touch alpha
    }

This last example, alpha is set to 0

I'm not used to work with vector, maybe i'm missing something...

**Comment by NicolasRannou** [comment]
yes exactly, we do not want to touch alpha when inverting, so if `dataValue.xyz = vec3(1.) - dataValue.xyz;` we should use that.

**Comment by eduardor2k** [comment]
@NicolasRannou the last commit already contains that correction, the PR is ready

**Comment by NicolasRannou** [comment]
@eduardor2k thanks!

**Comment by hurryhuang1007** [comment]
Is it still work? It's same broken at current master branch.

**Comment by NicolasRannou** [comment]
@hurryhuang1007 to set the opacity, should shall also make sure you set the material transparency to 'true':
```
    stackHelper.slice.opacity = 0.5;
    stackHelper.slice._material.transparent = true;
```

**Comment by hurryhuang1007** [comment]
@NicolasRannou very thanks! it has worked.

**Pull request merged**
