### PR TITLE
URL parse fix for API

### PR DESCRIPTION
**Pull request by JSibir**

### CODE REVIEW

**Comment by eduardor2k** [comment]
I think there's no need to check the file extension to see if it's a dicom file, because normally you will pass only a supported file type

**Comment by JSibir** [comment]
@eduardor2k however, `Loader` should receive from `Utils` proper extension/file type to choose proper `Parser`

**Comment by eduardor2k** [comment]
@JSibir you are right, the problem is DICOM files normally don't have extension, maybe it would be easier to remove the "dicom detection code" in `core.utils`.

static parseUrl(url) {
    const data = {};
    data.filename = '';
    data.extension = '';
    data.pathname = '';
    data.query = '';

    let parsedUrl = null;
    try {
      parsedUrl = new URL(url);
      // A relative url will throw an typeError exception
    } catch(e) {
      // we parse a relative url, if this url+base is incorrect, another exception will be thrown
      parsedUrl = new URL(url,location.origin);
    }

    data.pathname = parsedUrl.pathname;
    data.query = parsedUrl.search;
    data.filename = parsedUrl.searchParams.get('filename');

    // get file name
    if (!data.filename) {
      data.filename = data.pathname.split('/').pop();
    }

    // find extension
    let splittedName = data.filename.split('.');
    ~~if (splittedName.length <= 1) {
      data.extension = 'dicom';
    } else {~~
    if (splittedName.length > 1) {
      data.extension = data.filename.split('.').pop();
    }

    ~~if (!isNaN(data.extension)) {
      data.extension = 'dicom';
    }

    if (data.query &&
      data.query.includes('contentType=application%2Fdicom')) {
      data.extension = 'dicom';
    }~~

    return data;
  }

and try to load as a Dicom if the extension is not recognized in `loaders.volume`.

let Parser = null;

    switch (extension.toUpperCase()) {
      case 'NII':
      case 'NII_':
        Parser = ParsersNifti;
        break;
      case 'DCM':
      case 'DICOM':
      case 'IMA':
      case '':
        Parser = ParsersDicom;
        break;
      case 'MHD':
        Parser = ParsersMhd;
        break;
      case 'NRRD':
        Parser = ParsersNrrd;
        break;
      case 'MGH':
      case 'MGZ':
        Parser = ParsersMgh;
        break;
      default:
        try {
            Parser = ParsersDicom;
        } catch( e) {
            window.console.log('unsupported extension: ' + extension);
            return false;
        }
    }
    return Parser;
  }

**Comment by JSibir** [comment]
`ParsersDicom` is already a default parser, if extension is empty.
Use it for PDF or some other extensions isn't a good idea.

**Comment by eduardor2k** [comment]
@JSibir on `core.utils` if no extension is set

    if (splittedName.length <= 1) {
        data.extension = 'dicom';
    }

extension is set as "dicom", extension will never be "", that piece of code is redundant or the `case ''` will never be executed.

**Pull request merged**
