### PR TITLE
Fix URL parsing

### PR DESCRIPTION
**Pull request by eduardor2k**
See bug #309

### CODE REVIEW

**Comment by NicolasRannou** [comment]
Thanks!

**Comment by PtiLuky** [comment]
I have a problem with this merge : 
```new URL(url);``` 
needs to be 
``` new URL(url, base);``` 
with relative url, where base is the url to your root.

Is there a way to handle relative and absolute url ?
Or do we have to change all our URLs to absolute before using AMI ?

**Comment by NicolasRannou** [comment]
@PtiLuky can you put a concrete example of what `url` and `base` are in your case? for testing

**Comment by NicolasRannou** [comment]
may help
https://github.com/sindresorhus/is-absolute-url/blob/master/index.js

**Comment by NicolasRannou** [comment]
@PtiLuky , does using a `base` solve your problem?

I guess you can set `const base = location.href;`

**Comment by JSibir** [comment]
https://github.com/FNNDSC/ami/pull/317

**Comment by eduardor2k** [comment]
We could do:

    try {
        let parsedUrl = new Url(url);
    // A relative url will throw an typeError exception
    } catch(TypeError e) {
        // we parse a relative url, if this url+base is incorrect, another exception will be thrown
        let parsedUrl = new Url(url,base);
    }

    it should behave the same way as before

**Comment by JSibir** [comment]
@eduardor2k your PR will not solve the problem if files are downloaded by server side scripts (like, php, py, ...)

**Comment by eduardor2k** [comment]
@JSibir Hi, could you explain why it would not work for server side scripts? I'm unable to see the problem & I would like to know why it would not work. Thanks!

**Comment by JSibir** [comment]
Link: `/data.php?file_id=123`
After parsing we have `dicom.extension = 'php'` and get error `unsupported extension`

**Comment by eduardor2k** [comment]
@JSibir Thanks for explaining the problem, i was unable to see the problem, I see that we are trying to guess the format from the url, maybe it would be best to retrieve the response header and use the mime type first and filename as second option, if the file is supported download the file and try the matching parser.

**Comment by NicolasRannou** [comment]
@eduardor2k that suggestion sounds the best indeed.

I'll merge #318 right now because the url parsing is currently broken, then we can work on new setup from there!

Thanks

**Comment by eduardor2k** [comment]
@NicolasRannou yes, sorry about that!

**Pull request merged**
