### PR TITLE
Parser update & OpenJPEG integration

### PR DESCRIPTION
**Pull request by JSibir**
Work in progress

### CODE REVIEW

**Comment by NicolasRannou** [comment]
Nice, do you know what is different between with this fork of OpenJPEG and the cornerstone one?

**Comment by JSibir** [comment]
I found 3 differences:
- export fixes (can be used with node & webpack)
- memory limit is increased (some of my images can be opened only with this fix)
- encode method is added

Also, you should check test case which fails with new library.

**Comment by NicolasRannou** [comment]
https://github.com/universalsoftware/ami/blob/e443a45ce936e8bde3ab558d7b0e594145d22bad/specs/parsers/parsers.dicom.spec.js#L172

Should be `[0, 2403]`

**Comment by NicolasRannou** [comment]
Also, would you happen to a single small anonymized DICOM file that was not working before?
We need to add a test for it

**Comment by JSibir** [comment]
I sent 3 images to you last week. You may use them.

**Comment by NicolasRannou** [comment]
Also we probably do not need `"image-JPEG2000": "OHIF/image-JPEG2000#master",` anymore right?

**Comment by JSibir** [comment]
I'm not so sure.
If `OpenJPEG` opens 95% of images, and `image-JPEG2000` - about 80%, then probably the last one can opens 3%, which the first one can't.
Moreover, `OpenJPEG` may fail to initialize on some devices.

Lets leave `image-JPEG2000` till `0.0.25` release

**Comment by NicolasRannou** [comment]
`OpenJPEG may fail to initialize on some devices`do you know why? is it a known issue with OpenJPEG?

**Comment by JSibir** [comment]
I don't know for sure, but there are 2 checks in Cornerstone, for successful load and initialize. So, may be they have found some weird case.

**Comment by NicolasRannou** [comment]
OK can we add that in the comments with a link to cornerstone?

Also please see the comments I left in the code

**Comment by NicolasRannou** [comment]
Finally, we must add a test before merging:

File for reference: 
[s1_dl+.zip](https://github.com/FNNDSC/ami/files/2208956/s1_dl%2B.zip)

**Comment by JSibir** [comment]
Link to Cornerstone checks: https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/a9b408f5562bde5543fc6986bd23fbac9d676562/src/shared/decoders/decodeJPEG2000.js#L127-L134

**Pull request merged**
