### PR TITLE
ROI widget

### PR DESCRIPTION
**Pull request by okrad**
Since the ROI widget wasn't complete, I wrote a simpler version. This ROI currently works on rectangular regions only ("Slicer style"), but it could be enhanced to treat ellipsoidal areas.

I guess the implementation is a little bit "naive" in some points, hope anyway it can be of some help.

### CODE REVIEW

**Comment by NicolasRannou** [comment]
@okrad thanks! CAn you share a GIF of the widget in action?

**Comment by NicolasRannou** [comment]
@jgonzabal is it fine for you?

**Comment by okrad** [comment]
@JSibir, thank you, I think I'll take a look at your ellipse widget... Let me know if you need help with merging... 
I didn't look at your work, but I too have some ideas for widget improvements (for example, it would be really useful if the widgets could be styled through external css).

@NicolasRannou, here's a short video...
roi

**Comment by jgonzabal** [comment]
Hi, looks really nice, I would like to test the changes and see how affects the current tools, especially the angle. Also, the way the widgets are move, we might use a consistent strategy. Regarding the ROI statistics, are computed inside of the widget or outside? Looks like we have 3 implementations now. :)

**Comment by JSibir** [comment]
Will try to finish my branch in 24 hours and create PR (with video demonstration)

**Comment by NicolasRannou** [comment]
Closing as latest PR containing all changes has been merged - please re-open if needed

**Pull request closed without merging**
