### PR TITLE
Widgets: new and improved

### PR DESCRIPTION
**Pull request by JSibir**
- widget.angle is finished
- widget.rectangle is created (with RoI)
- widget.ellipse is created (with RoI)
- widget.polygon is created (with RoI)
- widget.roi renamed to widget.freehand and is improved
- widget.voxelProbe value calculation is corrected
- all widgets can be deleted (widget.free())
- all widgets can be hidden on frame change and shown back if we returns to frame where they were created (hide(), update targetMesh, show())
- a lot of other fixes and additions

p.s. Video is available in below comment
p.s.s. Some additional work will be done till Thursday (Polygon & Freehand dragging, ...)

### CODE REVIEW

**Comment by JSibir** [comment]
Forget to show that selected widgets can be deleted

**Comment by NicolasRannou** [comment]
Did you integrate changes from https://github.com/FNNDSC/ami/pull/288 by any chance?

**Comment by NicolasRannou** [comment]
Also, does it fix the offset between 3D and SVG we can currently see the the ami widgets example?
screen shot 2018-06-05 at 5 42 10 pm

**Comment by NicolasRannou** [comment]
Cool DICOM BTW, any chance this one is anonymized and we can use it in AMI's example for the widget?

**Comment by JSibir** [comment]
https://github.com/FNNDSC/ami/pull/288 has a little bit different approach. Moreover, it creates Rectangle widget from RoI. Values calculation algorithm is good for it, but can't be used for other figures (ellipse, polygon).
But it has several great functions and ideas,

Offset between Mesh and DOM isn't fixed because I don't see any reasons to show both. I want to add options to choose what will be shown (Mesh or DOM).

[Bonus DICOM](https://github.com/FNNDSC/ami/files/2074946/8c1fa987ea45fa558a6c33f91b319901.zip)

**Comment by NicolasRannou** [comment]
Thanks for the DICOM -

Could you integrate the great functions and ideas from @okrad by any chance?

Finally, the last missing piece is an upgrade guide from old widgets to new API!

Thanks!

**Comment by JSibir** [comment]
Upgrade guide:
- All widgets' constructors arguments order:
-- mesh (required)
-- controls (required)
-- stack (conditional, may be omitted for **annotation** and **angle**)
- widget.onEnd() doesn't have arguments

So much has to be done, so I don't sure about https://github.com/FNNDSC/ami/pull/288 integration. But if I have free time I'll definitely do it.

**Comment by okrad** [comment]
Kudos @JSibir, these widgets look really nice! 

If you think that there are some parts of my ROI that can be useful, feel free to integrate them.
Anyway I guess my PR can be closed, since your implementation provides and definitely improve the functionalities of my widget.

**Comment by JSibir** [comment]
@okrad you have nice label positioning in updateDOMPosition and some code refactor looks practical (screen2NDC, ndc2world), moreover, I can miss something useful
Don't sure I'll have time to merge this.

**Comment by okrad** [comment]
Hi @JSibir, I'm experimenting with your widgets but I have some problems in understanding how to interact with them... 
For example, the handle widget has an event handler for the "wheel" event, and that handler is the only place in which the "onMove" method is invoked. 
What I don't understand is why would I want to move the widget on the wheel event? I would expect the onMove method to be called inside a mouseenter/mousemove handler in conjunction with a mousedown/mouseup check, but probably I'm missing something...

**Comment by okrad** [comment]
Nevermind, I got it...
I'm having some issues with positioning and I got messed up looking at the code...
Still I don't understand what's going wrong with positioning, I'll let you know in case it turns out to be a problem with the widgets...

**Pull request merged**
