### PR TITLE
[Feature] Add TypeScript Support

### LINKED ISSUE #355: Add Typescript support
The objective of this PR is to help our migration process to TS.
We will be able to use both TS and JS then just get rid of JS when all the code has been ported to TS.

* Support TS and JS file (for smooth transition to type script)
* Generate JS bundles as before
* Generate definition files
* Add a .tslint configuration file for editors to nicely pick up changes
* Transpile every file to TS ?

### PR DESCRIPTION
**Pull request by AlexSwensen**
# Purpose
Adds typescript support, some basic lint rules, webpack configuration changes, and required packages.

closes #355 

## What does this pr do
- adds required packages for typescript and ts-loader
- adds to webpack configuration to transpile .ts files to .js
- adds tsconfig.json for typescript configuration
- converts ami.js to ami.ts
- adds rules to karma configuration
- ts definitions are exported to ./build
- adds some basic lint rules
## Where should the reviewer start
`webpack.config.build.js`
`src/ami.ts`
## Background Information
See #355 for relevant discussion

## Additional Notes
Feel free to debate and request changes. This is just what i could whip up in a short period of time. I'm happy for this to be an iterative change and for someone else to tackle cleaning up configs, adding rules, and converting files to TypeScript. I am also happy to help with any of those as well, but i think those make sense as separate PR's.

### CODE REVIEW

**Comment by ShawnToubeau** [comment]
Lgtm! 👍

**Comment by NicolasRannou** [comment]
Thanks, looking good!

@AlexSwensen Any thought on the comment from @ShawnToubeau:

>I have a question though when I run for example yarn example geometries_slice it defaults to 0.0.0.0:8080 instead of localhost:8080. Is this a bug?

Sounds fine to me bug maybe not?

**Comment by ShawnToubeau** [comment]
When it directs me to 0.0.0.0:8080 I get an ERR_SOCKET_NOT_CONNECTED but if I manually changed it to localhost:8080 it works. Wasn't sure if this was normal or if I was missing something?

**Comment by AlexSwensen** [comment]
@NicolasRannou @ShawnToubeau Not sure. I didn't change anything in that area to my knowledge. I am guessing it's unrelated. I'll do a comparison tonight to be sure.

**Comment by ShawnToubeau** [comment]
This was happening before I pulled your changes @AlexSwensen so I don't think it was anything you did.

**Comment by AlexSwensen** [comment]
@ShawnToubeau I would say it's unrelated then. 
I would open another issue for that and provide information like what system you are running on.

**Comment by AlexSwensen** [comment]
@NicolasRannou Unless you have any additional notes. I think this is good to go.

**Comment by NicolasRannou** [comment]
OK cool! Thanks

**Pull request merged**
