### PR TITLE
Minor Opacity fix

### PR DESCRIPTION
**Pull request by aalises**
Fixed opacity calculation inside the segmentationLUT Helper, it was not functioning correctly when the opacity was 0 due to the checks performed.

### CODE REVIEW

**Comment by NicolasRannou** [comment]
Hmm something when wrong, can you re-submit a pull request with just the latest commit from dev?

**Comment by aalises** [comment]
Yeah I don't know what happened, should only be one commit different... :O

**Comment by NicolasRannou** [comment]
Should I close it and you submit a new one from the latest #dev?

**Comment by aalises** [comment]
I have been trying for a while but I can't seem to only make a pull request with only the latest commit... :( all the other commits appear as well........

**Comment by NicolasRannou** [comment]
I could just add your changes on the dev branch without pull request if you do not mind

**Comment by aalises** [comment]
Finally could create the pull request 👍

**Comment by NicolasRannou** [comment]
Awesome!

**Pull request closed without merging**
