### PR TITLE
stack improvements

### PR DESCRIPTION
**Pull request by hurryhuang1007**
sort stack for multi-frame DICOM files by echoNumber, acquisitionNumber, inStackPositionNumber, instanceNumber and sliceLocation tags.

### CODE REVIEW

**Comment by hurryhuang1007** [comment]
@JSibir  @NicolasRannou 
I found the following rules from my existing data that can determine the frames from different stack.

1.The echoNumber is different.
2.The acquisitionNumber is different and sliceLocation is different also.
3.The inStackPositionNumber is different.

I have succeeded in dividing my existing multi-frame DICOM data into several stack based on these rules.

But it still has two problems.
1.The rawData of stack will be create by pack function, they should have been shared.
2.I know that this way of realization is a bit wrong,it is just a fast way.

I will add an attribute in stack to achieve the rawData sharing, but before that, I want to know if there is a better way to realize my feature.

**Comment by hurryhuang1007** [comment]
Oops,the c094341 and 65b08e8 commit are already included #338 PR.
If #338 PR be accepted, they will disappear in this PR.

**Comment by JSibir** [comment]
I test the performance of several multiframe US DICOM files.
If they merged into 1 stack, we should implement some more switching manage functions, but speed is better.
If separate stack is created for each file, then it takes approximately 1 second to switch from one stack to another. And doctors don't like this second.

**Comment by hurryhuang1007** [comment]
@JSibir  If you run the stack's prepare and pack methods beforehand, the seconds you say will be much less than you even feel

**Comment by JSibir** [comment]
@hurryhuang1007 slice.helper initialization also take time
I switched between two stacks in one series several times (so all initialization already was made) and creating new slice.helper each time takes this second

**Comment by hurryhuang1007** [comment]
@JSibir  I have just tested it again, and this second does exist.

But it is THREEJS's render methods takes 367.80 ms, because this page has three different views, the total time is about one second.

image

**Comment by JSibir** [comment]
@hurryhuang1007 Yep, so in our implementation we prefer not to have this second if it is possible.
So, for now, I try to use one stack with several multiframe files and manage scrolling, switching and playback by myself

**Comment by hurryhuang1007** [comment]
@JSibir 
But not creating multiple stack means that all data will be loaded into GPU memory, if that's true, memory consumption can be terrible when loading a DICOM data with 20 or more frames.
And on the sagittal and coronal views, it's strange that the DICOM data of multiple frames will be displayed one after another.

By the way, the problem you encounter is failure to load data or render data failed?

**Comment by JSibir** [comment]
@hurryhuang1007 I trieded to load a lot of small DICOMs and one huge DICOM, memory consumption is convenient for me (Chrome hit a snag only on > 2.2 Gb per tab)

On large series raw parsed data cannot be squeezed into textures (7 * 4K x 4K textures are available in current version of AMI), so I got black frames or THREEJS errors.

**Comment by hurryhuang1007** [comment]
@JSibir 
I care more about memory consumption than you do, because I will open multiple DICOM data on a single tab.
So I think it's configurable to be divided into several stack.

**Pull request closed without merging**
