### PR TITLE
Cancellation of loading files

### PR DESCRIPTION
**Pull request by JSibir**
Very useful on series with 100+ files.

Can be used like this:
```
let requests = new Map();
loader.load(files, requests).then(function () {
  requests = null;

```

```
requests.forEach(function (request) {
  request.abort();
});
```

### CODE REVIEW

**Comment by NicolasRannou** [comment]
@JSibir looking good - Can we add default values to token, so it is backward compatible?

**Comment by JSibir** [comment]
I believe it's already backward compatible.
It token isn't passed to loader then loader do nothing with it.

**Comment by NicolasRannou** [comment]
You are right @JSibir

Instead of a plain array to store tokens, would it make sense to use a map, to map the URL to the request?

In addition of only storing the abort function, may we should just store the request object so user can use it as needed.

Something like:
```
// requests is a map
requests.set(url, request);
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

Thoughts?

**Comment by NicolasRannou** [comment]
@JSibir I do not have a specific use case in mind but I can imagine that may be needed in the future

**Comment by JSibir** [comment]
I'll test it when finish with VolumeRenderring

**Pull request merged**
