### PR TITLE
Widgets review: handling of container offsets, simplified VoxelProbe

### PR DESCRIPTION
**Pull request by okrad**
Here's my patches...
Basically:
- `WidgetsBase` now has two new methods: `initOffsets` and `offsetChanged`. The first is called in the constructor of all widgets (actually it could be invoked directly in the WIdgetsBase constructor) to precalculate the container offsets and simplify mouse position calculations. The second one must be called when the container position changes: in the base form it recalculates the container offsets and calls `update`. Since these methods all work on a `_container` instance, I modified the WidgetsBase constructor to take the container as a parameter. Finally I added the `free` method, that in it's base form releases the container. Extending classes should implement logic to release used resources (eventhandlers, dom elements, ...).

- `WidgetsRuler` and `WidgetsHandle`: implemented needed parent methods

- `WidgetsVoxelProbe`: this is the class that changed the most... I made it extend `WidgetsBase` and overridden some methods. I (hope I) simplified the code as you suggested: now the widget uses only one `HelpersVoxel`. If more than one is needed it should be instantiated at the application level.

I hope I didn't mess up too much the code... :-)

### CODE REVIEW

**Comment by NicolasRannou** [comment]
Thanks a lot I'll look at it in details @okrad !

One thing that we may need is also to update the example to reflect the new API.

**Comment by NicolasRannou** [comment]
Fix for #121

**Comment by NicolasRannou** [comment]
Fix for #96

**Comment by NicolasRannou** [comment]
@okrad Looking good so far, I think I'll modify a couple of things, push it and let you know for review -

**Comment by okrad** [comment]
@NicolasRannou  Thank you!

**Comment by NicolasRannou** [comment]
Merged (finally..) I modified small things and there is still a fair amount that can be done to improve the widgets (show/hide functionality for instance) but that is all good for now!

**Pull request merged**
