### PR TITLE
URL parser fix v2

### PR DESCRIPTION
**Pull request by JSibir**

### CODE REVIEW

**Comment by eduardor2k** [comment]
Hi @JSibir thanks for the fix.

I'm unable to see the need to have two conditional constructors, if having a simple constructor wohtour regex is enough:

    let parsedUrl = new URL(url, location.origin);

if `url` is "/my_file.zip" and `location.origin` is 'http://www.google.com' => http://www.google.com/my_file.zip

if `url` is "http://www.google.com/my_file.zip" and `location.origin` is 'http://www.google.com' => http://www.google.com/my_file.zip
 
if `url` is "http://www.amazon.com/my_file.zip" and `location.origin` is 'http://www.google.com' => http://www.amazon.com/my_file.zip

Maybe there's a case, where using a simple constructor might not work?

**Comment by JSibir** [comment]
This case is confusing: `new URL('http://www.google.com/myfile.zip', 'http://www.otherdomain.com')`, so I try to made it clearer.
However, it can be optimized by removing regexp test.
Lets wait for @NicolasRannou opinion.

**Comment by NicolasRannou** [comment]
Reading now, it seems that after all:
```
let parsedUrl = new URL(url, location.origin);
```

`location.origin` ensures that "new URL" doesn't crash even if url is relative and if url is absolute, then location.origin is ignored.

@JSibir can you think of a use case where 'http://www.otherdomain.com'  is important in `new URL('http://www.google.com/myfile.zip', 'http://www.otherdomain.com')`?

**Comment by JSibir** [comment]
@NicolasRannou no, the first argument is more important always.

**Comment by NicolasRannou** [comment]
OK great, so we could also hard code the second argument in case of location.origin get some unexpected value - something like:

```
const parsedUrl = new URL(url, 'https://github.com/FNNDSC/ami');
```

**Comment by JSibir** [comment]
At least, something like:
```const domain = params.domain || location.origin,
  parsedUrl = new URL(url, domain);
```

so if user didn't pass domain, then `location.origin` is used by default.

**Comment by JSibir** [comment]
Adding `params` to AMI.Lodaer is a complex task.
I don't plan to do it in this branch.

It's easier to say that relative URL is unsupported for now if nodejs environment support is important.

**Comment by NicolasRannou** [comment]
Yes, I didn't realize params was not already there -
```
// Hard code domain so new URL works for both relative and absolute URLs
// Do not use location.origin to initialize the domain because it does not work
// in a Node environment.
// If url is absolute, domain is ignored in new URL.
const domain = 'https://github.com/FNNDSC/ami';
const parsedUrl = new URL(url, domain);
```

**Comment by eduardor2k** [comment]
We could use this polyfill?

https://www.npmjs.com/package/location-origin

**Comment by NicolasRannou** [comment]
since the only purpose of "location.origin" it to avoid new URL from crashing and that we do not use or need it at any point yet, let's keep it hard coded.

If we need it at some point we can explore solutions.

Polyfills will just make the library bigger.

Does it make sense?

**Comment by eduardor2k** [comment]
No really, for now i think it's a good compromise.

**Comment by JSibir** [comment]
With hardcoded domain, relative URL will be unsupported.
No one can use `/data.php?file=123` or `/file.dcm`, because file is stored not on `https://github.com/FNNDSC/ami`.

**Comment by eduardor2k** [comment]
Let me try this solution, maybe this URL is not used to fetch the file, only to validate file extension

**Comment by NicolasRannou** [comment]
Yes I see the potential problem now - so we will probably now go for 
```
const domain = location.origin;
parsedUrl = new URL(url, domain);
```

Then we should potentially use something like:
```
const domain = params.domain || location.origin;
const parsedUrl = new URL(url, domain);
```

**Comment by eduardor2k** [comment]
It's not used to fetch the files, only to validate the extension (I've just tried to load a relative url + full url, with the fixed domain).

    const domain = 'https://github.com/FNNDSC/ami';
    const parsedUrl = new URL(url, domain);

So, for now this *fix* should work for now

**Comment by eduardor2k** [comment]
imagen

**Comment by eduardor2k** [comment]
imagen

**Comment by JSibir** [comment]
May be `const parsedUrl = new URL(url, 'http://fix.me');`, so it looks like obvious todo?

**Comment by NicolasRannou** [comment]
thanks for testing @eduardor2k (cool screenshots btw :) ) , solution sounds good @JSibir ,

**Comment by eduardor2k** [comment]
@JSibir sounds good to me too

**Comment by NicolasRannou** [comment]
@JSibir can you declare 1 variable per line, and separate each declaration by a ";"?

**Comment by JSibir** [comment]
@NicolasRannou  I already done it in last commit

**Pull request merged**
