### PR TITLE
Added this.hasChanged

### PR DESCRIPTION
**Pull request by rwirz**
The control is related with a renderer.
It is not necessary to render if there is not update in the control. 
So, I created property called hasChanged to know when the user has done some event in the control.
The user MUST reset the variable to false in his program.

Should be it better to do something like this to do it more automatically?

function getHasChanged() {
    let aux = this.hasChanged;
    this.hasChanged=false;
    return aux;
}

### CODE REVIEW

**Comment by NicolasRannou** [comment]
@rwirz does it have a real impact on performance?

Could you please submit the patch to THREEJS?
We want to update the THREEJS because ideally AMI should not have to deal with that unless there is a good reason to maintain a different version.

The only other missing thing in THREEJS one is the ability to set the "state" programatically.
I just opened a pull request for this one:
https://github.com/mrdoob/three.js/pull/10284

Once merged, we could ideally just get rid of the copy of the controls we maintain in AMI.

Does that make sense?

**Comment by rwirz** [comment]
It is not for Three.js since the api is good, it is an application "issue".
How a re you going to work with the Views: 3d, axial, sagital, coronal in the same window ?
If you are going to work with orthogonal cameras for axial, sagital and coronal, it is good to render only when something change so the performance is better.

**Comment by NicolasRannou** [comment]
I think I understand what you mean - in the render loop, you want to render the scene only if something was updated, if not skip the render.

So basically you are asking if we can get a proper API to support this behavior:
http://jsfiddle.net/nicolasrannou/7k7bf7fc/

**Comment by rwirz** [comment]
Yes. You can see a great FPS difference. The problem is that you need a function to render the 2D view (3D scene with orthogonal camera) to render when the GUI is updated too. And with layers you can set what see or not see in each camera.

**Comment by NicolasRannou** [comment]
Yes  exactly - as you said my concern is that it is not specific to the `control` so I am not sure it is the best place to add such a flag:
- if the LUTs changes we need to re-render.
- if the window size changes we need to re-render.
- etc.

I am thinking now that maybe the best approach is not to have any flag at all and just render the scene explicitly if needed:
```
render: function(){
    requestAnimationFrame(function() {
      controls.update();
      renderer.render(scene, camera);
    });
}
```

It needs a bit more logic to handle zoom/pan properly though but that it is probably the best bet.

WDYT?

**Pull request closed without merging**
