### PR TITLE
Added first iteration segmentation LUT Helper class (Following method on Issue #173)

### PR DESCRIPTION
**Pull request by aalises**
First iteration on the **SegmentationLUT Helper** class (work in progress).

Right now each element of the LUT is defined as [w,x,y,z], where **w** is the label or voxel value of the specific element, and **(x,y,z)** is the color vector of the associated label in RGB from 0 to 255.

A 256x128px texture is then created and the pixels painted according to the label, so the position x:1,y:0 will be the first label, the position x:58,y:0 will be the label 58, and the x:6,y:1 will be label 262 (255 + 7, each row starts by index 0!).

TODO:
- Opacity right now is not managed but could be applied the same way the HelpersLUT does it for the discrete case (although making it separate would be better maybe?). 

-The **dict** contains each string label element by element of the LUT for rapid accessing. Putting the freesurfer colormap and labels inside as presets would be nice. 

-Parsing on the shader

### CODE REVIEW

**Comment by NicolasRannou** [comment]
Thanks! Checking the code now!

**Comment by NicolasRannou** [comment]
@aalises what do you think if instead of passing a color array, an opacity array and a dictionnay array to the constructor:
```
color = [[1, 140, 120, 80], [2, 120, 60, 170]],
 +   opacity = [[0, 0],[1, 1]], 
 +   dict = [[1,"Air"], [2,"Bone"]]
```

we could pas a "segmentation object":
```
// for instance
const freesurferSegmentation = {
0: {
  color: [0, 0, 0],
  opacity: 0,
  label: 'background',
},
1: {
  color: [255, 0, 0],
  opacity: 1,
  label: 'white matter',
},
etc.

```

That should make the API and mapping from voxel value to label value simpler.

Also maybe we should add a new directory inside the "helpers" directory to store the lut helpers and defaults:

```
src / helpers / lut / helpers.lut.color.js
                               helpers.lut.segmentation.js
                               presets /
                                 segmentation/ freesurfer.js
                                 color/ rainbow.js
                                            heat.js
```

Just thinking out loud - WDYT?

**Comment by NicolasRannou** [comment]
Also please use `'` instead of `"` when you extract the label!

**Comment by aalises** [comment]
Hi! I think it is a wonderful idea, at first when I was figuring out how the LUTs worked I was confused at how many things the constructor had, opacity and color but also lut and lut0 which were the same (enclosing color and opacity), so having it all unified into a segmentation object is wonderful.

Then, instead of presetLuts and presetDicts, we could have presetSegs, and we do not have to assign them differently. Will generate the FreesurferLUT using this new variable format on it today afternoon or tomorrow and commit it :)

**Comment by aalises** [comment]
And putting the presets on a separate file would be indeed cleaner as you can see that they are quite lengthy...

**Comment by NicolasRannou** [comment]
Thanks a lot! I am myself testing the parsing of this LUT on the shaders -
not quite there yet but on the way!

screen shot 2017-08-28 at 5 31 39 pm

**Comment by aalises** [comment]
Looking good! Changed the class variable names and added the segmentation object. Still have to generate the Freesurfer variables (I have the scripts on another computer), and fix some small things that hadn't noticed. Almost there 💃

**Comment by aalises** [comment]
Hello @NicolasRannou , the Freesurfer segmentation preset is now set and working. There was a problem in that the canvas height was 16 instead of 128 (as in the HelpersLUT) and hadn't noticed it until recently, so not all the values were parsed into the textures! Now it is changed so all the labels are mapped into the texture.

TODO: Put the presets into a separate class?

**Comment by NicolasRannou** [comment]
Awesome @aalises ! - yes it would be nice to have the presets in a separate file. we could add a directory in `src`:
```
src / presets / lut / segmentation / freesurfer (lut segmentation presets)
src / presets / lut / color / spectrum                 (lut color preset)
src / presets / lut / opacity / lowpass               (lut opacity preset)
src / presets / wl / ct-brain                               (lut window level preset)
...
```

Would that make sense?

I am also doing some progress on my end, I could visualize the segmentation lut properly but I am not sure why that works yet - got to take a deeper look :)

screen shot 2017-08-29 at 12 39 30 am

**Comment by aalises** [comment]
Hello @NicolasRannou ,

I have created a new module named presets that contain the **presetsSegmentation** class. I have also simplified the **segmentationLUT API** and the preset object to make it less confusing.

Right now the segmentationLUT allows to only get and set the **segmentation object** . The **presetSegmentation class** has the **preset object** which is essentially its segmentation object. So, if you want to create a segmentation LUT and add a preset to it just call:

```

let PresetsSegmentation = AMI.default.Presets.Segmentation;
...
  //Example seg
    const fsSeg = {0: {color: [0, 0, 0],opacity: 0,label: 'background'},
        1: {color: [255, 0, 0],opacity: 1,label: 'white matter'},
    };

  let lutLayerLblmap = new HelpersSegmentationLut(
        "my-lut-canvases-l1",
        "Freesurfer",
        fsSeg,
    );

    let presetsSeg = new PresetsSegmentation('Freesurfer'); //You set the preset with the ID and it gets the correspondant object from all the presets
    lutLayerLblmap.segmentation = presetsSeg.preset;

```

You can also add preset objects to the class and see the available presets. WDYT of this approach/simplification?

**Comment by NicolasRannou** [comment]
@aalises  great!

Yes I like the API, I think it is almost there - Couple of small things:
1- Rename `segObj` and `this._ segObj` to `segmentation` and `this._segmentation`
2- Add a default `segmentation` in the `HelpersSegmentationLut ` constructor (In case user doesn't provide any)
3- As you say, I think it would be great to directly include the presets
4- Simplify:
```
+      ctx.beginPath();
 +      ctx.strokeStyle = `rgba( ${Math.round(color[0])}, ${Math.round(color[1])}, ${Math.round(color[2])}, ${opacity})`;
 +      ctx.moveTo(xCoord, yCoord);
 +      ctx.lineTo(xCoord + 1, yCoord + 1); //One pixel step
 +      ctx.stroke();
 +      ctx.closePath();
```
by:
```
      ctx.fillStyle = `rgba( ${this._color[i][1]}, ${this._color[i][2]}, ${this._color[i][3]}, ${opacity})`;
      ctx.fillRect(xCoord, yCoord, 1, 1);
```

And that should be it :)

**Comment by NicolasRannou** [comment]
FYI - I pushed some stuff on the #dev branch to add support the the segmentation LUTs.
Basically you have to call:
```
      uniformsLayer1.uLutSegmentation.value = 1;
      uniformsLayer1.uTextureLUTSegmentation.value = lutLayer1.texture;
```

In general you also want to turn OFF interpolation for the "Segmentation" volume! Please let me know if it works for you!

**Comment by aalises** [comment]
Hello @NicolasRannou , I made the changes you requested and merged the dev branch into it with the shader changes (which work perfectly for me), so we have Freesurfer LUT support into AMI! :)

What do you think? Any other changes that need to be made?

**Comment by NicolasRannou** [comment]
Oh I'm sorry don't know what I was thinking - we can remove the preset segmentation from the helper and instead just define:
```
let defaultSegmentation = {
  0: {color: [0, 0, 0],opacity: 0,label: 'background'},
  1: {color: [255, 0, 0],opacity: 1,label: 'white matter'},
  };
...
constructor(containerID, segID = 'Freesurfer', segmentation = defaultSegmentation){
```

Apart from that I think we are good!

**Comment by NicolasRannou** [comment]
And last detail about the presets:
1- create a new `src/presets/presets.segmentation.freesurfer.js`
```
const segmentation = {
  0: {color: [0, 0, 0], opacity: 0, label: 'Unknown'},
  1: {color: [70, 130, 180], opacity: 1, label: 'Left-Cerebral-Exterior'},
  2: {color: [245, 245, 245], opacity: 1, label: 'Left-Cerebral-White-Matter'},
  3: {color: [205, 62, 78], opacity: 1, label: 'Left-Cerebral-Cortex'},
...
}

export default segmentation;
```
2- import this file in `src/presets/presets.segmentation.js`
```
import freesurferSegmentation from 'presets.segmentation.freesurfer';
...

+presetSegs() {
 +    return {
         Freesurfer: freesurferSegmentation,
}
```

**Comment by NicolasRannou** [comment]
Thanks a lot @aalises - did you have a chance to test it to make sure it works with the new shaders by any chance?
?

**Comment by aalises** [comment]
Hello @NicolasRannou , yes I did test the new shaders and they work like a charm :) , did it before merging the dev branch. From there the next steps regarding the LUTs would be separating the opacity LUTS, maybe adding some more segmentation presets and maybe simplifying the colorLUTs the same way as we did in the segmentation ones.

**Comment by NicolasRannou** [comment]
great! Yes I agree with you about the next step, ideally would be to have the same api for color, segmentation and opacity LUTs!

Thanks a lot!

**Comment by aalises** [comment]
No problem! Will be using AMI quite a lot in some projects, will let you know if I find something else that is lacking or if I encounter any problem during the development.

Cheers!

**Comment by NicolasRannou** [comment]
Yes any feedback is great! Basically now most of basic features should be there and time has come to consolidate structure/improve perf :) -
Also if you publish paper or work referencing AMI, I'd love to add references there https://github.com/FNNDSC/ami#citations so please do not hesitate to get in touch if interested!

**Comment by aalises** [comment]
Hi @NicolasRannou  , found a bug in the opacity calculation inside the helpers segmentationLUT. Basically how the "? :" is check, if the opacity is 0 as in the first element, the check will fail and the opacity put to 1, so in the example the opacities were not calculated correctly (as label 0 appeared completely opaque). The fix is simply to change the line 59 of the helper.segmentation lut where the opacity is computed inside the paintCanvas() to something like:

`let opacity = (typeof this._segmentation[i]['opacity'] != "undefined") ? this._segmentation[i]['opacity'] : 1;`
or
`let opacity = this:_segmentation[i]['opacity']`

Sorry for the inconvenience, just found it now when trying to mess with opacities of the different layers!

**Pull request merged**
