### PR TITLE
Widgets: additions

### PR DESCRIPTION
**Pull request by JSibir**
CrossRuler: labels and getDimensions() are added
**All widgets**: 3rd argument `params` is added to constructor

Widgets creations should be corrected for widgets which get stack in constructor:
`new Widgets<...>(stackHelper.slice.mesh, controls, stack);`
 ->
`new Widgets<...>(stackHelper.slice.mesh, controls, { stack: stack });`
`new Widgets<...>(stackHelper.slice.mesh, controls, { pixelSpacing: frame.pixelSpacing });` - for all rulers

Supported params: hideMesh (bool), hideHandleMesh (bool), stack (ModelStack), pixelSpacing

### CODE REVIEW

**Comment by NicolasRannou** [comment]
@JSibir thanks for the PR, can we make params the last parameter with a default value if the stack is required?

**Comment by JSibir** [comment]
@NicolasRannou I think different arguments order for different widgets is not a good practice.
Moreover, params already have default value and can be omiеted.

3 ways: 
- leave as is
- move stack inside params
- make stack required for all widgets, then params can be the last arg

**Comment by NicolasRannou** [comment]
@JSibir so I think we should move stack inside the parameters, and only provide the stack as a parameter is needed.

Some widgets only need the "pixelSpacing" (not the full stack), so in those cases, we would only pass the "pixelSpacing" to the widget.

Looking a https://github.com/FNNDSC/ami/blob/dev/src/widgets/widgets.ellipse.js#L325, is it actually correct that it is cm2 ? There may be a DICOM tag to get the actual scale?

**Comment by JSibir** [comment]
Only limited number of modalities provide actual scale in DICOM tags. CI units is a default one if `pixelSpacing` is set.
I will implement US advanced measurements in this 2 weeks (in another branch).

Will implement your suggestions about `params` today.

**Comment by NicolasRannou** [comment]
@JSibir Closing - please let me know if that should stay open

**Pull request closed without merging**
